---
- hosts: 192.168.1.214
  gather_facts: false
  connection: network_cli
  collections:
    - arista.eos.eos

  tasks:
#    - name: Add a vlan
#      arista.eos.eos_vlans:
#        config:
#          - name: "{{ name }}"
#          - state: "active"
#          - vlan_id: "{{ vlan_id }}"
#          - state: merged
    - name: Copy using inline content
      ansible.builtin.copy:
        content: '# This file was moved to /etc/other.conf'
        dest: /ansible/test.txt